node-url = "http://chain:8545"
simulation-node-url = "http://chain:8545"

[run-loop]
solve-deadline = "20s"

[logging]
filter = "warn,autopilot=debug,shared=info,price_estimation=info"

[current-block]
poll-interval = "1s"

[[gas-estimators]]
type = "Web3"

[[gas-estimators]]
type = "Alloy"

[[drivers]]
name = "pysolver"
url = "http://driver/pysolver"
address = "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f"

[fee-policies]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"

[ethflow]
skip-event-sync = true

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[native-price-estimation.cache]
max-age = "20m"

[order-quoting]
# price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]
price-estimation-drivers = [{ name = "pysolver", url = "http://driver/pysolver" }]
