[[solver]]
name = "pysolver" # Arbitrary name given to this solver, must be unique
endpoint = "http://pysolver"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
account = "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97" # Known test private key

[submission]
gas-price-cap = "1000000000000"

[[submission.mempool]]
mempool = "public"

[liquidity]
base-tokens = [
    "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d", # WXDAI
    "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1", # WETH
    "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83", # USDC
    "0x9C58BAcC331c9aa871AFD802DB6379a98e80CEdb", # GNO
]

[[liquidity.uniswap-v2]]
preset = "honeyswap"
